config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :juegos

  map.resources :temas, :has_many => :comentarios, :path_names => { :new => 'nueva', :edit => 'editar' }

  map.resources :estudiantes, :path_names => {:new =>"nuevo", :edit => "editar"}

    map.resources :mensajes, :path_names => {:new =>"nuevo", :edit => "editar"}
  
    map.login "login", :controller => "user_sessions", :action => "new"
    map.logout "logout", :controller => "user_sessions", :action => "destroy"
    map.registro "registro", :controller =>"users", :action=>"new"
    map.resources :grupos_estudiantiles, :path_names => { :new => 'nuevo', :edit => 'editar' }
    map.resources :universidades, :path_names => { :new => 'nueva', :edit => 'editar' }
    map.resources :actividades, :has_many => :comentarios, :path_names => { :new => 'nueva', :edit => 'editar' }
    map.resources :noticias, :has_many => :comentarios, :path_names => { :new => 'nueva', :edit => 'editar' }
    map.resources :user_sessions, :as =>"cuenta"
    map.resources :users, :as => 'usuarios', :path_names => {:new=>'nuevo', :edit => 'editar' }    
    map.register '/register/:activation_code', :controller => 'activations', :action => 'new'
    map.activate '/activate/:id', :controller => 'activations', :action => 'create'

  

   map.root :controller => "actividades"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  #validate :rol_debe_ser_igual_o_menor_al_del_creador
  belongs_to :grupo_estudiantil
  has_attached_file :photo, :styles => { :small => "180x180>" },
  :url => "/uploads/users/:attachment/:id/:style/:basename.:extension",
  :path => ":rails_root/public/uploads/users/:attachment/:id/:style/:basename.:extension"
  validates_attachment_size :photo,  :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png','image/gif']
  
  has_many :mensajes_recibidos, :class_name => 'Mensaje', :foreign_key => 'receptor_id', :order=> "created_at DESC", :dependent => :destroy
  has_many :mensajes_enviados, :class_name => 'Mensaje', :foreign_key => 'emisor_id', :order=> "created_at DESC", :dependent => :destroy
  has_many :assignments, :dependent => :destroy
  has_many :roles, :through =>:assignments
  
  def self.search(term)
  if term
    find(:all, :conditions => ['login LIKE ?', "%#{term}%"])
  else
    find(:all)
  end
end

  def active?
    active
  end
  # added to user.rb
  def activate!
    self.active = true
    save
  end
  def deliver_activation_instructions!
      reset_perishable_token!
      Notifier.deliver_activation_instructions(self)
    end

    def deliver_activation_confirmation!
      reset_perishable_token!
      Notifier.deliver_activation_confirmation(self)
    end
	

def role_symbols
  roles.map do |role|
    role.name.underscore.to_sym
  end
end


	def grupo_estudiantil_nombre
		grupo_estudiantil.nombre if grupo_estudiantil
	end
	
	def grupo_estudiantil_nombre=(nombre)
		self.grupo_estudiantil=GrupoEstudiantil.find_by_nombre(nombre) unless nombre.blank?
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
filter_resource_access

def index
	@usuarios = User.search(params[:term])
end

  def new    
  end
  
  def create
    @user = User.new(params[:user])
	@user.active=true
	parametros_de_usuarios_convencionales
    if @user.save_without_session_maintenance
      redirect_to users_path
    else
      render :action => :new
    end
  end
  
  def show
  end
  
  def destroy
  @user.destroy
  redirect_to users_url
  end
  
 
  def edit
  end
  
  def update
  parametros_de_usuarios_convencionales
    if @user.update_attributes(params[:user])
      flash[:notice] = "Cuenta actualizada!"
      redirect_to users_path
    else
      render :action => :edit
    end
  end
  
    def parametros_de_usuarios_convencionales
  if !has_role? :admin
	role=Role.find(3)
		assignment=Assignment.new
		assignment.role=role
		assignment.user=@user
		assignment.save
		@user.grupo_estudiantil=current_user.grupo_estudiantil
	end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<%= form.label :login %><br />
<%= form.text_field :login %><br />
<br />
<%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
<%= form.password_field :password %><br />
<br />
<%= form.label :password_confirmation %><br />
<%= form.password_field :password_confirmation %><br />
<br />
<%= form.label :email %><br />
<%= form.text_field :email %><br />
<br >
<% if current_user.admin? %>
<%= form.label :roles %><br />
<%= form.collection_select(:role_ids,Role.all,:id,:name) %><br >
<br />
<%= form.label :grupo_estudiantil %><br />
<%= form.collection_select(:grupo_estudiantil_ids,GrupoEstudiantil.all,:id,:nombre) %><br >
<%end%>

app/views/users/edit.html.erb
<% content_for :head do%>
<script type="text/javascript">
	$(function() {
		$("#user_grupo_estudiantil_nombre").autocomplete({
			source: "<%=grupos_estudiantiles_path(:format => "json")%>"
		});
	});
	</script>
<% end %>
<h1>Editar usuario</h1>
<% form_for @user, :html=> {:multipart=>true}  do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </p>
      <p>
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </p>
  <p>
	<%= f.label :password, f.object.new_record? ? nil : "Change password" %><br />
	<%= f.password_field :password %><br />
	</p>
	<p>
	<%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation %><br />
	</p>
  <p>
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>	
  </p>
  <p>
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>	
  </p>
  <p>
    <%= f.label :cedula %><br />
    <%= f.text_field :cedula %>	
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>	
  </p>
  <%if has_role? :admin%>
  <p>
  <%= f.label :role_ids, "Roles" %><br />
<%= f.collection_select(:role_ids,Role.all,:id,:name) %><br />
</p>
<p>
<%= f.label :grupo_estudiantil_nombre %><br />
<%= f.text_field :grupo_estudiantil_nombre%>
</p>
<%end%>
  <p>
    <%= f.submit 'Actualizar Usuario' %>
  </p>
<% end %>
<br />

app/views/users/index.html.erb
<% content_for :head do %>  
<%= javascript_include_tag 'jquery.dataTables' %>  
<%= stylesheet_link_tag 'demo_table_jui' %>
<script type="text/javascript">
$(document).ready(function() {

	$('#usuarios').dataTable({
	 "bJQueryUI": true,
		"aoColumns": [
			null,
             { "bSortable": false },
            null,
            null,
           { "bSortable": false }
        ],
                     "oLanguage": {
					 "sUrl": "dataTables.spanish.txt"
			}           
	});
});
</script>
 <% end %>
<h1>Usuarios</h1>

<table id="usuarios">
<thead>
  <tr>
    <th>Login</th>
	<th>Nombre</th>
    <th>Grupo Estudiantil</th>
    <th>Rol</th>
	<th></th>
  </tr>
</thead>
<tbody>
<% @usuarios.each do |usuario| %>
  <tr>
    <td><%=link_to usuario.login, usuario %></td>
	<td><%="#{usuario.nombre} #{usuario.apellido}"%></td>
    <td>
		<% if usuario.grupo_estudiantil%>
			<%=link_to usuario.grupo_estudiantil.nombre, usuario.grupo_estudiantil%>
		<% else %>
			No tiene
		<% end%>
	</td>
    <td><%=h usuario.roles.first.name %></td>
    <td>
	<%=link_authorized :edit, usuario,'<span class="ui-icon ui-icon-pencil" title="Editar"></span>', edit_user_path(usuario)%> 
	<%= link_authorized :destroy, usuario, '<span class="ui-icon ui-icon-trash" title="Eliminar"></span>', usuario %>
	</td>
  </tr>
<% end %>
</tbody>
</table>
<br />

app/views/users/index.json.erb
<%=
'[' + (
   @usuarios.map do |u|
     %Q[{ "id": "#{u.login}" , "label": "#{u.login}" , "value": "#{u.login}" }]
   end.join(',')
) + ']'
%>

app/views/users/new.html.erb
<% content_for :head do%>
<script type="text/javascript">
	$(function() {
		$("#user_grupo_estudiantil_nombre").autocomplete({
			source: "<%=grupos_estudiantiles_path(:format => "json")%>"
		});
	});
	</script>
<% end %>

<h1>Registro de Usuario</h1>
<% form_for @user, :html=> {:multipart=>true}  do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </p>
    <p>
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </p>
  <p>
	<%= f.label :password, f.object.new_record? ? nil : "Change password" %><br />
	<%= f.password_field :password %><br />
	</p>
	<p>
	<%= f.label :password_confirmation %><br />
	<%= f.password_field :password_confirmation %><br />
	</p>
  <p>
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>	
  </p>
  <p>
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>	
  </p>
  <p>
    <%= f.label :cedula %><br />
    <%= f.text_field :cedula %>	
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>	
  </p>
  <p>
    <%if has_role? :admin%>
  <%= f.label :role_ids, "Roles" %><br />
<%= f.collection_select(:role_ids,Role.all,:id,:name) %><br />
</p>
<p>
<%= f.label :grupo_estudiantil_nombre %><br />
<%= f.text_field :grupo_estudiantil_nombre%>
</p>
<%end%>
  <p>
    <%= f.submit 'Crear Usuario' %>
  </p>
<% end %>
<br />

app/views/users/show.html.erb
<h1>  <%="#{h @user.nombre} #{h @user.apellido}" %></h1>
<%=image_tag @user.photo.url(:small)%>

<p>
  <b>Login:</b>
  <%=h @user.login %>
</p>
<p>
  <b>Enviar mensaje:</b>
  <%= link_to @user.login, new_mensaje_path({:receptor=>@user.login}) %>
</p>
<p>
  <b>Email:</b>
  <%=h @user.email %>
</p>

<p>
  <b>Nombre:</b>
  <%=h @user.nombre %>
</p>